on: [push, pull_request]

jobs:
  sonar:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Run only unit test
      - name: Build, Unit test, Package and Sonar analysis
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar --file pom.xml -s $GITHUB_WORKSPACE/.m2/settings.xml
        shell: bash
