on: [push, pull_request]

jobs:
  sonar:
    runs-on: ubuntu-latest
    name: Sonar Scanner
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Run only unit test
      - name: Build, Unit test, Package and Sonar analysis
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar
        shell: bash
